apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  labels:
    app: nexus
spec:
  replicas: 1
  selector:
       matchLabels:
         app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
        - name: nexus
          image: sonatype/nexus3:latest
          resources:
            limits:
              memory: 2Gi
              cpu: "1"
            requests:
              memory: 500Mi
              cpu: 250m
          env:
          - name: NEXUS_CONTEXT
            value: mou-nexus

---
apiVersion: v1
kind: Service
metadata:
  name: nexus
spec:
  selector:
    app: nexus
  type: LoadBalancer
  ports:
    - port: 8081
